# Single Soliton Configuration
# Date: 2025-08-13
# Authors: Sandy H. S. Herho, Iwan P. Anwar, Faruq Khadami, 
#          Fikry P. Lugina, Rusmawan Suwarman, Dasapta E. Irawan

scenario_name: "Single Soliton"

# Domain parameters (comparable across all scenarios)
domain_length: 50.0
num_points: 512

# Time integration (comparable across all scenarios)
t_final: 20.0
n_snapshots: 100

# Initial condition parameters
initial_condition: "single_soliton"
amplitude: 2.0
position: -10.0
velocity: 1.0

# Numerical solver settings
method: "DOP853"  # 8th-order Dormand-Prince for high accuracy
rtol: 1.0e-9      # Relative tolerance
atol: 1.0e-11     # Absolute tolerance
max_step: 0.1     # Maximum step size

# Performance and stability options
use_numba: true           # Enable JIT compilation
use_adaptive: true        # Adaptive time-stepping
use_filtering: true       # Anti-aliasing filter (2/3 rule)
monitor_conservation: true # Monitor conserved quantities

# Output settings
save_netcdf: true
save_animation: true
fps: 20
dpi: 100

# Output directory (relative to package)
output_dir: "../outputs"
log_dir: "../logs"
