# Two Soliton Collision Configuration
# Date: 2025-08-13
# Authors: Sandy H. S. Herho, Iwan P. Anwar, Faruq Khadami,
#          Rusmawan Suwarman, Dasapta E. Irawan

scenario_name: "Two Soliton Collision"

# Domain parameters (comparable across all scenarios)
domain_length: 50.0
num_points: 512

# Time integration (comparable across all scenarios)
t_final: 20.0
n_snapshots: 100

# Initial condition parameters
initial_condition: "two_soliton"
A1: 2.0    # Amplitude of first soliton
A2: 1.5    # Amplitude of second soliton
x1: -10.0  # Initial position of first soliton
x2: 10.0   # Initial position of second soliton
v1: 2.0    # Velocity of first soliton (rightward)
v2: -2.0   # Velocity of second soliton (leftward)

# Numerical solver settings
method: "DOP853"  # 8th-order Dormand-Prince for high accuracy
rtol: 1.0e-9      # Relative tolerance
atol: 1.0e-11     # Absolute tolerance
max_step: 0.1     # Maximum step size

# Performance and stability options
use_numba: true           # Enable JIT compilation
use_adaptive: true        # Adaptive time-stepping
use_filtering: true       # Anti-aliasing filter (2/3 rule)
monitor_conservation: true # Monitor conserved quantities

# Output settings
save_netcdf: true
save_animation: true
fps: 20
dpi: 100

# Output directory (relative to package)
output_dir: "../outputs"
log_dir: "../logs"
